### PR TITLE
Fix pmt when interest rate is 0

### LINKED ISSUE #10: pmt returns NaN if interest rate is 0
Hi there! 

Thanks for all your work on this gem. It's saved me a lot of time in my project. 

I'm trying to use `Exonio.pmt` with an interest rate of 0 and I'm getting an unexpected result:

```
(byebug) interest_rate.to_s
"0.0"
(byebug) Exonio.pmt(interest_rate / 12, loan.amortization_schedule - month + 1, 0 - beginning_contract_balance)
#<BigDecimal:7ffd1dc47350,'NaN',9(45)>
```

In excel, it seems to work if I use a rate of 0: 

screen shot 2018-07-13 at 11 17 17 am

I don't know enough about these formulas so I don't know what's the best solution. 

What could be the best patch for this? 

Please let me know.

Thanks!

### PR DESCRIPTION
**Pull request by rmm5t**
Fixes #10. `pmt` returned `NaN` when passed a rate of `0.0`. 

(#10 was mistakenly closed prematurely)

## BEFORE

```
>> Exonio::VERSION
=> "0.7.0"
>> Exonio.pmt(0.0, 36, 36_000)
=> NaN
```

## AFTER

```
>> Exonio.pmt(0.0, 36, 36_000)
=> -1000
```

### CODE REVIEW

File: lib/exonio/financial.rb [hunk 1]
```diff
@@ -119,6 +119,8 @@ def nper(rate, pmt, pv, fv = 0, end_or_beginning = 0)
     #   Exonio.pmt(0.075/12, 12*15, 200_000) # ==> -1854.0247200054619
     #
     def pmt(rate, nper, pv, fv = 0, end_or_beginning = 0)
+      return -(pv - fv) / nper if rate.zero?
```
Comment (julianolf) [inline lib/exonio/financial.rb:122]: First of all, thanks for noticing the issue and opening this PR.

I wasn't sure about the formula, so I decided to check the test cases you added using NumPy Financial, and I got a different output for the second test case.

Running it against NumPy's implementation of the [PMT](https://numpy.org/numpy-financial/latest/pmt.html#numpy_financial.pmt) function, the returned result was `-1500` instead of `-500`.

To double-check, I used this [online calculator](https://www.calculator.net/finance-calculator.html), and the results matched those from NumPy.

Looking at NumPy's source code, I saw that the formula actually adds `fv` to `pv` before inverting the sign.

```python
# When `rate` is equal to 0, `tmp` is equal to 1 and `fact` is equal to `nper`
return -(fv + pv * temp) / fact
```

You can take a look at the full source code [here](https://github.com/numpy/numpy-financial/blob/f1a43fabd7cc51105cd7ac60c55465e7117c1519/numpy_financial/_financial.py#L262).

I will gladly merge this PR if you can fix the formula.

**Comment by rmm5t** [comment]
given the partial build matrix failures, I'm going to submit another PR to help fix those.

**Review by julianolf — CHANGES_REQUESTED** [review]

File: lib/exonio/financial.rb (hunk 1 above)
Comment (rmm5t) [reply lib/exonio/financial.rb:122]: Wait, I'm confused. I must completely misunderstand the meaning of `fv` (future value), but I concur that Excel and Google Sheets also have the same behavior that you pointed to.

I will fix.

Comment (rmm5t) [reply lib/exonio/financial.rb]: Fixed. Thanks.

**Review by julianolf — APPROVED** [review]

**Comment by julianolf** [comment]
Thanks for the contribution @rmm5t!
